-- NITRO (BETA) Database Schema for Supabase PostgreSQL
-- Run this script directly in your Supabase Project's SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- ==========================================
-- 1. AUTH & IDENTITY DOMAIN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT DEFAULT '',
  bio TEXT DEFAULT '',
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member', -- 'owner', 'admin', 'vip', 'member'
  avatar_url TEXT DEFAULT '',
  pro_chat_glow TEXT DEFAULT 'gold',
  pro_custom_flair TEXT DEFAULT '',
  is_banned BOOLEAN DEFAULT false,
  is_proxy_banned BOOLEAN DEFAULT false,
  ban_reason TEXT DEFAULT '',
  proxy_timeout_until TIMESTAMPTZ,
  proxy_violations_count INT DEFAULT 0,
  banned_until TIMESTAMPTZ,
  muted_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  profile_name TEXT NOT NULL,
  favorites JSONB DEFAULT '[]'::jsonb,
  theme_settings JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ip_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  username TEXT NOT NULL,
  ip_address TEXT NOT NULL,
  user_agent TEXT DEFAULT '',
  location_info TEXT DEFAULT 'Unknown',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.banned_ips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address TEXT UNIQUE NOT NULL,
  reason TEXT DEFAULT 'Violation of platform terms',
  banned_by TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. GAMING SYSTEM DOMAIN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT DEFAULT '',
  author TEXT DEFAULT 'Community',
  thumbnail_url TEXT NOT NULL,
  embed_type TEXT NOT NULL DEFAULT 'iframe_url', -- 'iframe_url', 'html_code', 'builtin'
  embed_content TEXT NOT NULL,
  is_vip BOOLEAN DEFAULT false,
  category TEXT DEFAULT 'Action',
  clicks BIGINT DEFAULT 0,
  created_by TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.game_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  game_id BIGINT REFERENCES public.games(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, game_id)
);

CREATE TABLE IF NOT EXISTS public.game_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  details TEXT NOT NULL,
  username TEXT DEFAULT 'Guest',
  game_url TEXT DEFAULT '',
  upvotes INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.game_play_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  playtime_seconds INT DEFAULT 60,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. REAL-TIME COMMUNICATION DOMAIN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  username TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member',
  message TEXT NOT NULL,
  is_deleted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.direct_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  receiver_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  sender_username TEXT NOT NULL,
  receiver_username TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.private_rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_code TEXT UNIQUE NOT NULL,
  created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.filter_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word TEXT UNIQUE NOT NULL,
  filter_type TEXT DEFAULT 'both' -- 'chat', 'username', 'both'
);

-- ==========================================
-- 4. GOVERNANCE & MODERATION DOMAIN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.moderation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  admin_username TEXT NOT NULL,
  target TEXT NOT NULL,
  reason TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blocked_domains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain TEXT UNIQUE NOT NULL,
  reason TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 5. SYSTEM & ENGAGEMENT DOMAIN
-- ==========================================
CREATE TABLE IF NOT EXISTS public.site_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  alert_type TEXT DEFAULT 'info',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.community_polls (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  options JSONB NOT NULL,
  created_by TEXT DEFAULT 'admin',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.poll_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id BIGINT REFERENCES public.community_polls(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  option_index INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(poll_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.update_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- PERFORMANCE INDEXES
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);
CREATE INDEX IF NOT EXISTS idx_games_category ON public.games(category);
CREATE INDEX IF NOT EXISTS idx_games_slug ON public.games(slug);
CREATE INDEX IF NOT EXISTS idx_ip_logs_ip ON public.ip_logs(ip_address);
CREATE INDEX IF NOT EXISTS idx_ip_logs_username ON public.ip_logs(username);
CREATE INDEX IF NOT EXISTS idx_chat_created_at ON public.chat_messages(created_at);

-- Initial Seed Data: Filter Words
INSERT INTO public.filter_words (word, filter_type)
VALUES 
  ('slur1', 'both'),
  ('slur2', 'both'),
  ('hate', 'both'),
  ('nazi', 'both'),
  ('admin_impersonator', 'both')
ON CONFLICT (word) DO NOTHING;

-- Initial Seed Data: Games Catalog
INSERT INTO public.games (title, slug, author, thumbnail_url, embed_type, embed_content, is_vip, category, clicks)
VALUES
  ('Ragdoll Archers', 'ragdoll-archers', 'Eric Gurt', 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=500&auto=format&fit=crop&q=60', 'builtin', 'archers', false, 'Action', 20),
  ('Death Run 3D', 'death-run-3d', 'FLAY', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&auto=format&fit=crop&q=60', 'builtin', 'deathrun', false, 'Action', 19),
  ('Slope Runner', 'slope', 'Y8 Games', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=60', 'builtin', 'slope', false, 'Skill', 17),
  ('Brotato Survival', 'brotato', 'Blobfish', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=60', 'builtin', 'brotato', false, 'Action', 10),
  ('Geometry Dash Lite', 'geometry-dash-lite', 'RobTop Games', 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=60', 'builtin', 'geometry', false, 'Rhythm', 9),
  ('Deal or No Deal', 'deal-or-no-deal', 'Endemol', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=500&auto=format&fit=crop&q=60', 'builtin', 'deal', false, 'Puzzle', 8),
  ('2048 Deluxe', '2048', 'Gabriele Cirulli', 'https://images.unsplash.com/photo-1606167668584-78701c57f13d?w=500&auto=format&fit=crop&q=60', 'builtin', '2048', false, 'Puzzle', 45),
  ('8 Ball Classic Pool', '8-ball-classic', 'Famobi', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&auto=format&fit=crop&q=60', 'builtin', '8ball', false, 'Sports', 32),
  ('1v1.LOL Arena (VIP)', '1v1-lol', 'JustPlay.LOL', 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&auto=format&fit=crop&q=60', 'builtin', '1v1', true, 'Shooter', 64),
  ('A Bite at Freddy''s (VIP)', 'bite-at-freddys', 'Garrett McKay', 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=60', 'builtin', 'freddys', true, 'Horror', 53),
  ('Retro 64-in-1 Arcade', 'retro-64-arcade', 'NES Emulators', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=500&auto=format&fit=crop&q=60', 'builtin', 'retro', false, 'Retro', 28),
  ('A Small World Cup', 'small-world-cup', 'Rujogames', 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=60', 'builtin', 'soccer', false, 'Sports', 14)
ON CONFLICT (slug) DO NOTHING;

